name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "40 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 4b6f642c3c99fc76c08fa912e023d46a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
